namespace ZUEPC.Base.Enums.Institutions;

public enum InstitutionType
{
	UNKNOWN = 0,
	COLLEGE = 1,
	SLOVAK_ACADEMY_OF_SCIENCE = 2,
	SCIENTIFIC_RESEARCH_INSTITUTE = 3,
	EVENT_ORGANIZER = 4,
	GRANT_AGENCY = 5,
	DATABASE_PRODUCER = 6,
	AWARDING_INSTITUTION = 7,
	PUBLISHER_WITH_REVIEWED_PROCEEDINGS_EVIDENCE = 8,
	PUBLISHER_HAS_NO_REVIEWING_INFORMATION = 9,
	PUBLISHER_RENOWNED = 9,
	OTHER = 10,
	PUBLISHER = 11,
	INTELLECTUAL_PROPERTY_OFFICE = 12
}