namespace ZUEPC.Import.Enums.Person;

public enum PersonToPublicationRoleType
{
	UNKNOWN = 0,
	AUTHOR = 1,
	COMPILER = 2,
	REVIEWER = 3,
	TRANSLATOR = 4,
	PUBLISHER = 5,
	DISTRIBUTOR = 6,
	PRINTER = 7,
	IMPRESSION = 8,
	EDITOR_IN_CHIEF = 9,
	EXECUTIVE_EDITOR = 10,
	EDITOR = 11,
	CHAIRMAN_OF_THE_EDITORIAL_BOARD = 12,
	EDITOR_COMPILER = 13,
	AUTHOR_CORRESPONDENCE = 14,
	AUTHOR_COMMENTS = 15,
	AUTHOR_INTRODUCTION = 16,
	AUTHOR_AFTERWORD = 17,
	AUTHOR_INTERVIEW = 18,
	AUTHOR_INTERVIEWEE = 19,
	AUTHOR_PHOTOGRAPHS = 20,
	AUTHOR_GRAPHICS = 21,
	AUTHOR_MUSIC = 22,
	AUTHOR_CARTOGRAPHER = 23,
	AUTHOR_PROGRAMMER = 24,
	EDITOR_CRITICAL = 25
}