namespace ZUEPC.Base.Enums.Person;

public enum PersonWorkplacePositionType
{
	UNKOWN = 0,
	ASSISTANT = 1,
	DOCENT = 2,
	VISITING_PROFESSOR = 3,
	LECTURER = 4,
	FELLOW = 5,
	PROFESSOR = 6,
	RESEARCHER_SUPPORT = 7,
	RESEARCHER_TECHNIC = 8,
	RESEARCHER_RESEARCHER = 9,
	RESEARCHER_FOREIGN = 10,
	TEACHER_FOREIGN = 11,
	TEACHER_NO_RATIO = 12,
	RESEARCHER_NO_RATIO = 13,
	PHD_EXTERNAL = 14,
	PHD_INTERNAL = 15,
	OTHER = 16
}